models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self,fullname,email,phone):
        self.fullname=fullname
        self.email=email
        self.phone=phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONECTION_URI



#Congif File.


app = Flask(__name__)

#Flash using to send msg for any action doing.

app.secret_key="secret key"


#Data Base

app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_CONECTION_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"]=False
SQLAlchemy(app)


# Import blueprint to use the routes in the folder routes

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db


# Blueprints to separate the app into many parts and have control of all theroute used.

contacts = Blueprint("contacts", __name__)

# All the routes working from get method.

#Form and List


@contacts.route("/")
def home():
    # Listing all the data
    contacts = Contact.query.all()

    # for i in contacts:
    #     print (i.id)
    # Test the for to show all the elements.

    return render_template("index.html", contacts=contacts)

############## CREATE FUNCTION################


@contacts.route("/new", methods=["POST"])
def add_contact():
    #     # request allow to see the data sent in the POST methods
    fullname = request.form["fullname"]
    email = request.form["email"]
    phone = request.form["phone"]

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()

    flash("Contact added")

# #This print is just to check the values are coming
    print(new_contact)
    print(fullname)
    return redirect("/")

############## UPDATE FUNCTION################


@contacts.route("/update/<id>", methods=["POST", "GET"])
def update(id):

    # This conditional is to know if the info is comming from POST or GET method, if the info is comming for a GET it will make consult of the values but if is comming from a POST is going to make the update.
    #
    contact = Contact.query.get(id)
    if request.method == "POST":
        
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]


        db.session.commit()

        flash("Contact Updated")
        
        print("Contact Updated")
        return redirect(url_for("contacts.home"))
    else:
        contact = Contact.query.get(id)

    return render_template("update.html", contact=contact)

############## DELETE FUNCTION################
# If the route has another value after the name of the route, its means it needs another value to work, in this case delete url needs the id to delete the contact.
# And the functions it self need the same value as well like this:


@contacts.route("/delete/<id>")
def delete(id):
    # contact=Contact.query.get(id)
    db.session.delete(Contact.query.get(id))
    db.session.commit()

    print("Contact Deleted")

    flash("Contact Deleted")

    return redirect(url_for("contacts.home"))

templates/index.html
{% extends  "layout.html"  %}

{% block body %} 


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home Page</title>
  </head>
  <body>
    <h1>Home Page</h1>



    {%with messages =get_flashed_messages()%}
     {%if messages %}
     {%for message in messages%} 
     <div class="alert alert-success" role="alert">
      {{message}} 
    </div>

    {%endfor%}
    {%endif%} 
    {%endwith%}

    <form action="/new" method="POST" class="card">
      <label for="fullname"> <b><center> Write Full Name</center></b></label>
      <input type="text" name="fullname" placeholder="Your name" />
      <label for="email"><b> <font color="black"> <center>Write Email</center></font> </b></label>
      <input type="email" name="email" placeholder="Your email" />
      <label for="phone"> <b> <font color="black"> <center>Write Phone</center></font></b></label>
      <input type="text" name="phone" placeholder="Your phone" />
<br>
      <button class="btn btn-primary">Save</button>
    </form>

    <hr />

    <div>
      {% for item in contacts %}

      <div>
        <h5>{{item.fullname}}</h5>

        <p>{{item.email}}</p>
        <p>{{item.phone}}</p>

        <div>
          <a href="{{url_for('contacts.update', id=item.id)}}" class="btn btn-primary btn-sm">Update</a>
          <!--In this case i will use the function url_for to call the function delete, this because the function needs the id to delete the contact, and the function  does not allow or acept another parameter BUT url_for from Flask does.-->


          <a href="{{url_for('contacts.delete', id=item.id)}}" class="btn btn-danger btn-sm">Delete</a>
        </div>
        <hr>
      </div>

      {% endfor %}
    </div>
  </body>


</html>

{%endblock%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flask CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  </head>
  <body>



{% include("/partials/_navbar.html")%}

<div class="container p-2">
    {% block body %} {%endblock%}
</div>



  </body>
</html>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <font color="White">Flask CRUD </font>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      style="color: white"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon" style="color: white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/"> <font color="White"> Home </font></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{% extends  "layout.html"  %}

{% block body %} 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Updating</title>
  </head>
  <body>
    <h1>Updating Contact</h1>
    <hr>

    <form action="/update/{{contact.id}}" method="POST">
      <input
        type="text"
        name="fullname"
        placeholder="Your name"
        value="{{contact.fullname}}"
      />
      <input
        type="email"
        name="email"
        placeholder="Your email"
        value="{{contact.email}}"
      />
      <input
        type="text"
        name="phone"
        placeholder="Your phone"
        value="{{contact.phone}}"
      />

      <button class="btn btn-primary btn-sm">Update</button>
    </form>
  </body>
</html>

{%endblock%}